### PR TITLE
✨ Update api

### PR DESCRIPTION
**Pull request by YannickFricke**

### CODE REVIEW

**Comment by DmitryScaletta** [comment]
Thanks for the PR.
I think it requires some manual changes, for example here:
https://github.com/DmitryScaletta/twitch-api-swagger/pull/3/files#diff-a9865368a7fc7fa33065e35b2343f10d08fb79d65205435403d0a163a3044713R5750

I'll update it by myself later.

**Comment by YannickFricke** [comment]
I could also make a GitHub action which runs everyday and creates a PR when something changes :)

**Comment by DmitryScaletta** [comment]
> I could also make a GitHub action which runs everyday and creates a PR when something changes :)

It's not possible because they have a lot of mistakes in the docs and they constantly add the new ones almost every update.
So I have to manually fix it each time: 
https://github.com/DmitryScaletta/twitch-api-swagger/blob/main/scripts/utils/normalizeReferenceHtml.ts#L32

**Comment by DmitryScaletta** [comment]
Updated: https://github.com/DmitryScaletta/twitch-api-swagger/commit/1957f480e0135e8c1415cc7af37c2fdaba5ee761

**Comment by YannickFricke** [comment]
> > I could also make a GitHub action which runs everyday and creates a PR when something changes :)
> 
> It's not possible because they have a lot of mistakes in the docs and they constantly add the new ones almost every update. So I have to manually fix it each time: [`main`/scripts/utils/normalizeReferenceHtml.ts#L32](https://github.com/DmitryScaletta/twitch-api-swagger/blob/main/scripts/utils/normalizeReferenceHtml.ts?rgh-link-date=2024-08-02T06%3A37%3A36Z#L32)

Yeah I see - but then you would get notified when a change was made to the docs :)

But anyways - thanks for the update! :)

**Pull request closed without merging**
